### ISSUE TITLE
Support for unix domain sockets ?

### ISSUE THREAD

**Issue by mingodad** [caikelun/libsvx#2]
Hello !
I noticed there is no support for unix domain sockets, is this intentional ?
Cheers !

**Comment by caikelun** [comment]
Yes and no. I think the performance of local TCP sockets is good enough, and have better scalability. And... I've never used unix domain sockets in any actual projects, so...

**Comment by mingodad** [comment]
Also I noticed that it doesn't seem to support multiple listeners per server, like if we extend it to use as http/https, or having a console only listening on localhost/specific ip address, ...
Cheers !

**Comment by caikelun** [comment]
Yes, you're right, that‘s a problem. I'll add multiple listeners for TCP server module ASAP. Thanks~

**Comment by caikelun** [comment]
@mingodad  Hi! 
The multiple listeners support for TCP server has been added in 1697c9984f59fd50484525b5590ea012727c201e
